apiVersion: v1
kind: ConfigMap
metadata:
  namespace: anotherclass-321
  name: api-tester-3212-properties
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-3212
    version: 3.0.0
    managed-by: kubectl
data:
  spring_profiles_active: "dev"
  application_role: "ALL"
  postgresql_filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"
  termination_message-path: "/usr/src/myapp/log/termination.message"