apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-321
  name: api-tester-3212
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-3212
    version: 3.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-3212
  ports:
    - port: 80
      targetPort: http
      nodePort: 30212
  type: NodePort
