apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: anotherclass-323
  name: database-3231
  labels:
    part-of: k8s-anotherclass
    component: database
    name: database
    instance: api-tester-3231
    version: 3.0.0
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: k8s-anotherclass
      component: database
      name: database
      instance: database-3231
  replicas: 2
  template:
    metadata:
      labels:
        part-of: k8s-anotherclass
        component: database
        name: database
        instance: database-3231
        version: 3.0.0
    spec:
      containers:
        - name: database-3231
          image: 1pro/api-tester:3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: api-tester-3231-properties
          startupProbe:
            httpGet:
              path: "/startup"
              port: 8080
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: secret-datasource
              mountPath: /usr/src/myapp/datasource
            - name: longhorn-volume
              mountPath: /data/db
      volumes:
        - name: secret-datasource
          secret:
            secretName: api-tester-3231-postgresql
  volumeClaimTemplates:
    - metadata:
        name: longhorn-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10M
        storageClassName: "longhorn"